#s line to define a global platform for your project
 platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

#处理日期
 pod 'DateTools'
 pod 'Masonry'
 pod 'FMDB'
 pod 'RESideMenu'
